project_id = "ipnywrvwszqlaykbkske"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.advance-billing]
    verify_jwt = false
  [functions.send-push-notifications]
    verify_jwt = false
  [functions.generate-vapid-keys]
    verify_jwt = false
