uploads = []
generated = []

[[outputs]]
id = "rfmEG7Hpf7WT7T1A1dqsp"
uri = "file://public/demo-script.pdf"
type = "pdf"
title = "Unsubscribely — Demo Video Script (4 pages)"

[[outputs]]
id = "eW0LOVLKqQF7fceMAQdu2"
uri = "file://public/demo-script-video.pdf"
type = "pdf"
title = "Unsubscribely — Demo Script (5 pages)"

[[outputs]]
id = "6bhZlZuG95FQ4HGFcQfNc"
uri = "file://unsubscribely-demo-script.pdf"
type = "pdf"
title = "Unsubscribely — Demo Video Script (4 pages)"
