/**
 * Algorand smart contract interaction layer.
 *
 * Uses pre-compiled ARC-4 TEAL v11 artifacts (puyapy 5.7.1).
 * All deployment and method calls use correct ARC-4 method selectors.
 * No Supabase edge function dependency for contract operations.
 */

import algosdk from "algosdk"
import type { VaultType } from "./constants"

import EscrowVaultSpec from "../../../smart_contracts/artifacts/EscrowVault/EscrowVault.arc56.json"
import AgentEscrowVaultSpec from "../../../smart_contracts/artifacts/AgentEscrowVault/AgentEscrowVault.arc56.json"
import TimeLockSpec from "../../../smart_contracts/artifacts/TimeLockEscrow/TimeLockEscrow.arc56.json"
import MultiSigSpec from "../../../smart_contracts/artifacts/MultiSigEscrow/MultiSigEscrow.arc56.json"
import DisputeSpec from "../../../smart_contracts/artifacts/DisputeEscrow/DisputeEscrow.arc56.json"
import ASASpec from "../../../smart_contracts/artifacts/ASAEscrow/ASAEscrow.arc56.json"

// ── ARC-4 method selectors (extracted from compiled TEAL) ──────────────────
//
// Each selector = first 4 bytes of sha512_256(method_signature).
// These are deterministic — generated by puyapy from the Python source.
//
const SEL = {
  // Shared across all vault types
  delete:  new Uint8Array([0x24, 0x37, 0x8d, 0x3c]), // delete()void
  kill:    new Uint8Array([0xb9, 0xc2, 0x11, 0x55]), // kill()void
  release: new Uint8Array([0x07, 0x6b, 0xbd, 0x4d]), // release()void

  // Per-vault create selectors (differ by signature)
  createAddr:       new Uint8Array([0xcc, 0x69, 0x4e, 0xaa]), // create(address)void         — EscrowVault
  createAddrUint64: new Uint8Array([0xc0, 0xb6, 0x43, 0x52]), // create(address,uint64)void   — TimeLockEscrow, ASAEscrow
  createAddrAddr:   new Uint8Array([0x8a, 0x96, 0x98, 0x0e]), // create(address,address)void  — MultiSigEscrow, DisputeEscrow

  // Method-specific
  approve: new Uint8Array([0xd6, 0x11, 0xdb, 0xd8]), // approve()void  — MultiSigEscrow
  optin:   new Uint8Array([0xdc, 0x0d, 0xe7, 0xeb]), // optin()void    — ASAEscrow
}

// ── Artifact loader ────────────────────────────────────────────────────────

type Arc56Spec = {
  byteCode: { approval: string; clear: string }
  state: { schema: { global: { ints: number; bytes: number }; local: { ints: number; bytes: number } } }
}

function b64ToBytes(b64: string): Uint8Array {
  return new Uint8Array(atob(b64).split("").map((c) => c.charCodeAt(0)))
}

interface ArtifactData {
  approvalBytes: Uint8Array
  clearBytes: Uint8Array
  numGlobalInts: number
  numGlobalByteSlices: number
  numLocalInts: number
  numLocalByteSlices: number
}

function loadArtifact(spec: Arc56Spec): ArtifactData {
  return {
    approvalBytes: b64ToBytes(spec.byteCode.approval),
    clearBytes: b64ToBytes(spec.byteCode.clear),
    numGlobalInts: spec.state.schema.global.ints,
    numGlobalByteSlices: spec.state.schema.global.bytes,
    numLocalInts: spec.state.schema.local.ints,
    numLocalByteSlices: spec.state.schema.local.bytes,
  }
}

function artifactForType(type: VaultType): ArtifactData {
  const map: Record<VaultType, Arc56Spec> = {
    standard:   EscrowVaultSpec as Arc56Spec,
    time_locked: TimeLockSpec as Arc56Spec,
    multi_sig:  MultiSigSpec as Arc56Spec,
    dispute:    DisputeSpec as Arc56Spec,
    asa:        ASASpec as Arc56Spec,
  }
  return loadArtifact(map[type])
}

// ── Helpers ────────────────────────────────────────────────────────────────

function extractTxId(response: unknown): string {
  if (typeof response === "string") return response
  const r = response as Record<string, unknown>
  return String(r?.txid ?? r?.txId ?? r?.["txId"] ?? "")
}

function addrBytes(address: string): Uint8Array {
  return algosdk.decodeAddress(address).publicKey
}

type SignFn = (txn: algosdk.Transaction) => Promise<Uint8Array[]>

// ── Core deployment ────────────────────────────────────────────────────────

interface DeployResult { appId: number; appAddress: string; txnId: string }

async function deployApp(
  algodClient: algosdk.Algodv2,
  sender: string,
  artifact: ArtifactData,
  appArgs: Uint8Array[],
  signTransaction: SignFn,
): Promise<DeployResult> {
  const params = await algodClient.getTransactionParams().do()

  const txn = algosdk.makeApplicationCreateTxnFromObject({
    sender,
    suggestedParams: params,
    onComplete: algosdk.OnApplicationComplete.NoOpOC,
    approvalProgram: artifact.approvalBytes,
    clearProgram: artifact.clearBytes,
    numGlobalInts: artifact.numGlobalInts,
    numGlobalByteSlices: artifact.numGlobalByteSlices,
    numLocalInts: artifact.numLocalInts,
    numLocalByteSlices: artifact.numLocalByteSlices,
    appArgs,
  })

  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  const result = await algosdk.waitForConfirmation(algodClient, txnId, 4)
  const appId = Number(
    (result as any).applicationIndex ?? (result as any)["application-index"] ?? 0
  )
  if (appId === 0) throw new Error("Failed to retrieve application ID after deployment")
  const appAddress = String(algosdk.getApplicationAddress(appId))
  return { appId, appAddress, txnId }
}

// ── Vault deployment functions ─────────────────────────────────────────────

/** Deploy a standard escrow vault (EscrowVault.arc56). */
export async function deployEscrowContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("standard"),
    [SEL.createAddr, addrBytes(recipientAddress)],
    signTransaction,
  )
}

/**
 * Deploy an Agent-Managed Escrow Vault (AgentEscrowVault.arc56).
 *
 * Creator = senderAddress (user's wallet) — can kill and get refund.
 * Agent  = agentAddress — autonomous AI agent that releases on billing date.
 * Recipient = recipientAddress — subscription service that receives payment.
 *
 * This is the core contract for A2A Autonomous Payments (Agentic Commerce #3).
 */
export async function deployAgentEscrowContract(
  algodClient: algosdk.Algodv2, senderAddress: string,
  recipientAddress: string, agentAddress: string,
  signTransaction: SignFn,
): Promise<DeployResult> {
  const spec = AgentEscrowVaultSpec as Arc56Spec
  return deployApp(
    algodClient, senderAddress,
    loadArtifact(spec),
    [SEL.createAddrAddr, addrBytes(recipientAddress), addrBytes(agentAddress)],
    signTransaction,
  )
}

/** Deploy a time-locked escrow vault (TimeLockEscrow.arc56). */
export async function deployTimeLockContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  unlockTimestamp: number, signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("time_locked"),
    [SEL.createAddrUint64, addrBytes(recipientAddress), algosdk.encodeUint64(unlockTimestamp)],
    signTransaction,
  )
}

/** Deploy a 2-of-2 multi-sig escrow vault (MultiSigEscrow.arc56). */
export async function deployMultiSigContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  coSignerAddress: string, signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("multi_sig"),
    [SEL.createAddrAddr, addrBytes(recipientAddress), addrBytes(coSignerAddress)],
    signTransaction,
  )
}

/** Deploy a dispute-resolution escrow vault (DisputeEscrow.arc56). */
export async function deployDisputeContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  arbitratorAddress: string, signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("dispute"),
    [SEL.createAddrAddr, addrBytes(recipientAddress), addrBytes(arbitratorAddress)],
    signTransaction,
  )
}

/** Deploy an ASA token escrow vault (ASAEscrow.arc56). */
export async function deployASAContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  assetId: number, signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("asa"),
    [SEL.createAddrUint64, addrBytes(recipientAddress), algosdk.encodeUint64(assetId)],
    signTransaction,
  )
}

// ── Fund vault ─────────────────────────────────────────────────────────────

/**
 * Send ALGO to the escrow vault's application address.
 * The extra 100_000 µALGO covers the minimum balance requirement.
 */
export async function fundEscrowContract(
  algodClient: algosdk.Algodv2, senderAddress: string, appAddress: string,
  amountMicroAlgos: number, signTransaction: SignFn,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  const txn = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
    sender: senderAddress, receiver: appAddress,
    amount: amountMicroAlgos + 100_000,
    suggestedParams: params,
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  await algosdk.waitForConfirmation(algodClient, txnId, 4)
  return txnId
}

// ── ARC-4 NoOp method calls ────────────────────────────────────────────────

/**
 * Call a NoOp method on an application using the correct ARC-4 selector.
 * extraFee=true sets fee=2000 to cover one inner transaction (1000 outer + 1000 inner).
 */
async function callMethod(
  algodClient: algosdk.Algodv2, sender: string, appId: number,
  selector: Uint8Array, signTransaction: SignFn,
  extraFee = false,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  const txn = algosdk.makeApplicationCallTxnFromObject({
    sender, appIndex: appId,
    onComplete: algosdk.OnApplicationComplete.NoOpOC,
    suggestedParams: extraFee ? { ...params, fee: 2000, flatFee: true } : params,
    appArgs: [selector],
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  await algosdk.waitForConfirmation(algodClient, txnId, 4)
  return txnId
}

export async function releaseEscrowFunds(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  signTransaction: SignFn,
): Promise<string> {
  return callMethod(algodClient, senderAddress, appId, SEL.release, signTransaction, true)
}

export async function killEscrowContract(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  signTransaction: SignFn,
): Promise<string> {
  return callMethod(algodClient, senderAddress, appId, SEL.kill, signTransaction, true)
}

export async function approveMultiSig(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  signTransaction: SignFn,
): Promise<string> {
  return callMethod(algodClient, senderAddress, appId, SEL.approve, signTransaction, true)
}

export async function optinASA(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  signTransaction: SignFn,
): Promise<string> {
  return callMethod(algodClient, senderAddress, appId, SEL.optin, signTransaction, true)
}

export async function deleteEscrowContract(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  signTransaction: SignFn,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  const txn = algosdk.makeApplicationCallTxnFromObject({
    sender: senderAddress, appIndex: appId,
    onComplete: algosdk.OnApplicationComplete.DeleteApplicationOC,
    suggestedParams: { ...params, fee: 2000, flatFee: true },
    appArgs: [SEL.delete],
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  await algosdk.waitForConfirmation(algodClient, txnId, 4)
  return txnId
}

// ── NFT receipt minting ────────────────────────────────────────────────────

export async function mintNFTReceipt(
  algodClient: algosdk.Algodv2, senderAddress: string, vaultAppId: number,
  amount: number, recipientAddress: string,
  signTransaction: SignFn,
): Promise<{ assetId: number; txnId: string }> {
  const params = await algodClient.getTransactionParams().do()
  const metadata = {
    standard: "arc3",
    name: `Payment Receipt — Vault #${vaultAppId}`,
    description: `Escrow vault payment of ${amount} ALGO`,
    properties: { app_id: vaultAppId, amount, recipient: recipientAddress, timestamp: new Date().toISOString() },
  }
  const note = new TextEncoder().encode(JSON.stringify(metadata))
  const txn = algosdk.makeAssetCreateTxnWithSuggestedParamsFromObject({
    sender: senderAddress, suggestedParams: params,
    total: 1, decimals: 0, defaultFrozen: false,
    unitName: "RCPT", assetName: `Receipt-${vaultAppId}`,
    note,
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  const result = await algosdk.waitForConfirmation(algodClient, txnId, 4)
  const assetId = Number((result as any)["asset-index"] ?? (result as any).assetIndex ?? 0)
  return { assetId, txnId }
}

// ── ASA transfer to app ────────────────────────────────────────────────────

export async function sendASAToApp(
  algodClient: algosdk.Algodv2, senderAddress: string, appAddress: string,
  assetId: number, amount: number,
  signTransaction: SignFn,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  const txn = algosdk.makeAssetTransferTxnWithSuggestedParamsFromObject({
    sender: senderAddress, receiver: appAddress,
    assetIndex: assetId, amount, suggestedParams: params,
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  await algosdk.waitForConfirmation(algodClient, txnId, 4)
  return txnId
}
