/**
 * Algorand smart contract interaction layer.
 *
 * Uses pre-compiled ARC-4 TEAL v11 artifacts (puyapy 5.7.1).
 * All deployment and method calls use correct ARC-4 method selectors.
 * No Supabase edge function dependency for contract operations.
 */

import algosdk from "algosdk"
import type { VaultType } from "./constants"

import EscrowVaultSpec from "../../../smart_contracts/artifacts/EscrowVault/EscrowVault.arc56.json"
import AgentEscrowVaultSpec from "../../../smart_contracts/artifacts/AgentEscrowVault/AgentEscrowVault.arc56.json"
import AgentEscrowVaultV2Spec from "../../../smart_contracts/artifacts/AgentEscrowVaultV2/AgentEscrowVaultV2.arc56.json"
import TimeLockSpec from "../../../smart_contracts/artifacts/TimeLockEscrow/TimeLockEscrow.arc56.json"
import MultiSigSpec from "../../../smart_contracts/artifacts/MultiSigEscrow/MultiSigEscrow.arc56.json"
import DisputeSpec from "../../../smart_contracts/artifacts/DisputeEscrow/DisputeEscrow.arc56.json"
import ASASpec from "../../../smart_contracts/artifacts/ASAEscrow/ASAEscrow.arc56.json"

// ── ARC-4 method selectors (extracted from compiled TEAL) ──────────────────
//
// Each selector = first 4 bytes of sha512_256(method_signature).
// These are deterministic, generated by puyapy from the Python source.
//
const SEL = {
  // Shared across all vault types
  delete:  new Uint8Array([0x24, 0x37, 0x8d, 0x3c]), // delete()void
  kill:    new Uint8Array([0xb9, 0xc2, 0x11, 0x55]), // kill()void
  release: new Uint8Array([0x07, 0x6b, 0xbd, 0x4d]), // release()void

  // Per-vault create selectors (differ by signature)
  createAddr:       new Uint8Array([0xcc, 0x69, 0x4e, 0xaa]), // create(address)void        , EscrowVault
  createAddrUint64: new Uint8Array([0xc0, 0xb6, 0x43, 0x52]), // create(address,uint64)void  , TimeLockEscrow, ASAEscrow
  createAddrAddr:   new Uint8Array([0x8a, 0x96, 0x98, 0x0e]), // create(address,address)void , MultiSigEscrow, DisputeEscrow

  // Method-specific
  approve: new Uint8Array([0xd6, 0x11, 0xdb, 0xd8]), // approve()void , MultiSigEscrow
  optin:   new Uint8Array([0xdc, 0x0d, 0xe7, 0xeb]), // optin()void   , ASAEscrow
}

// ── Artifact loader ────────────────────────────────────────────────────────

type Arc56Spec = {
  byteCode: { approval: string; clear: string }
  state: { schema: { global: { ints: number; bytes: number }; local: { ints: number; bytes: number } } }
}

function b64ToBytes(b64: string): Uint8Array {
  return new Uint8Array(atob(b64).split("").map((c) => c.charCodeAt(0)))
}

interface ArtifactData {
  approvalBytes: Uint8Array
  clearBytes: Uint8Array
  numGlobalInts: number
  numGlobalByteSlices: number
  numLocalInts: number
  numLocalByteSlices: number
}

function loadArtifact(spec: Arc56Spec): ArtifactData {
  return {
    approvalBytes: b64ToBytes(spec.byteCode.approval),
    clearBytes: b64ToBytes(spec.byteCode.clear),
    numGlobalInts: spec.state.schema.global.ints,
    numGlobalByteSlices: spec.state.schema.global.bytes,
    numLocalInts: spec.state.schema.local.ints,
    numLocalByteSlices: spec.state.schema.local.bytes,
  }
}

function artifactForType(type: VaultType): ArtifactData {
  const map: Record<VaultType, Arc56Spec> = {
    standard:    EscrowVaultSpec as Arc56Spec,
    agent:       AgentEscrowVaultSpec as Arc56Spec,
    agent_v2:    AgentEscrowVaultV2Spec as Arc56Spec,
    time_locked: TimeLockSpec as Arc56Spec,
    multi_sig:   MultiSigSpec as Arc56Spec,
    dispute:     DisputeSpec as Arc56Spec,
    asa:         ASASpec as Arc56Spec,
  }
  return loadArtifact(map[type])
}

// ── Helpers ────────────────────────────────────────────────────────────────

function extractTxId(response: unknown): string {
  if (typeof response === "string") return response
  const r = response as Record<string, unknown>
  return String(r?.txid ?? r?.txId ?? r?.["txId"] ?? "")
}

function addrBytes(address: string): Uint8Array {
  return algosdk.decodeAddress(address).publicKey
}

type SignFn = (txn: algosdk.Transaction) => Promise<Uint8Array[]>

// ── Core deployment ────────────────────────────────────────────────────────

interface DeployResult { appId: number; appAddress: string; txnId: string }

async function deployApp(
  algodClient: algosdk.Algodv2,
  sender: string,
  artifact: ArtifactData,
  appArgs: Uint8Array[],
  signTransaction: SignFn,
): Promise<DeployResult> {
  const params = await algodClient.getTransactionParams().do()

  const txn = algosdk.makeApplicationCreateTxnFromObject({
    sender,
    suggestedParams: params,
    onComplete: algosdk.OnApplicationComplete.NoOpOC,
    approvalProgram: artifact.approvalBytes,
    clearProgram: artifact.clearBytes,
    numGlobalInts: artifact.numGlobalInts,
    numGlobalByteSlices: artifact.numGlobalByteSlices,
    numLocalInts: artifact.numLocalInts,
    numLocalByteSlices: artifact.numLocalByteSlices,
    appArgs,
  })

  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  const result = await algosdk.waitForConfirmation(algodClient, txnId, 4)
  const appId = Number(
    (result as any).applicationIndex ?? (result as any)["application-index"] ?? 0
  )
  if (appId === 0) throw new Error("Failed to retrieve application ID after deployment")
  const appAddress = String(algosdk.getApplicationAddress(appId))
  return { appId, appAddress, txnId }
}

// ── Vault deployment functions ─────────────────────────────────────────────

/** Deploy a standard escrow vault (EscrowVault.arc56). */
export async function deployEscrowContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("standard"),
    [SEL.createAddr, addrBytes(recipientAddress)],
    signTransaction,
  )
}

/**
 * Deploy an Agent Escrow Vault **v2** (AgentEscrowVaultV2.arc56). v2 adds an
 * explicit-amount `release(uint64)` method and writes BillingRecord entries
 * into Box Storage (`h:<cycle>`) for an immutable on-chain audit trail.
 * Persist the resulting vault with `vault_type: "agent_v2"` so release flows
 * route to `releaseAgentVaultV2` instead of the v1 `release()void` selector.
 */
export async function deployAgentEscrowContractV2(
  algodClient: algosdk.Algodv2, senderAddress: string,
  recipientAddress: string, agentAddress: string,
  signTransaction: SignFn,
): Promise<DeployResult> {
  const spec = AgentEscrowVaultV2Spec as Arc56Spec
  return deployApp(
    algodClient, senderAddress,
    loadArtifact(spec),
    [SEL.createAddrAddr, addrBytes(recipientAddress), addrBytes(agentAddress)],
    signTransaction,
  )
}

/** Deploy a time-locked escrow vault (TimeLockEscrow.arc56). */
export async function deployTimeLockContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  unlockTimestamp: number, signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("time_locked"),
    [SEL.createAddrUint64, addrBytes(recipientAddress), algosdk.encodeUint64(unlockTimestamp)],
    signTransaction,
  )
}

/** Deploy a 2-of-2 multi-sig escrow vault (MultiSigEscrow.arc56). */
export async function deployMultiSigContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  coSignerAddress: string, signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("multi_sig"),
    [SEL.createAddrAddr, addrBytes(recipientAddress), addrBytes(coSignerAddress)],
    signTransaction,
  )
}

/** Deploy a dispute-resolution escrow vault (DisputeEscrow.arc56). */
export async function deployDisputeContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  arbitratorAddress: string, signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("dispute"),
    [SEL.createAddrAddr, addrBytes(recipientAddress), addrBytes(arbitratorAddress)],
    signTransaction,
  )
}

/** Deploy an ASA token escrow vault (ASAEscrow.arc56). */
export async function deployASAContract(
  algodClient: algosdk.Algodv2, senderAddress: string, recipientAddress: string,
  assetId: number, signTransaction: SignFn,
): Promise<DeployResult> {
  return deployApp(
    algodClient, senderAddress,
    artifactForType("asa"),
    [SEL.createAddrUint64, addrBytes(recipientAddress), algosdk.encodeUint64(assetId)],
    signTransaction,
  )
}

// ── Fund vault ─────────────────────────────────────────────────────────────

/**
 * Send ALGO to the escrow vault's application address.
 * The extra 100_000 µALGO covers the minimum balance requirement.
 */
export async function fundEscrowContract(
  algodClient: algosdk.Algodv2, senderAddress: string, appAddress: string,
  amountMicroAlgos: number, signTransaction: SignFn,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  const txn = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
    sender: senderAddress, receiver: appAddress,
    amount: amountMicroAlgos + 100_000,
    suggestedParams: params,
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  await algosdk.waitForConfirmation(algodClient, txnId, 4)
  return txnId
}

// ── ARC-4 NoOp method calls ────────────────────────────────────────────────

/**
 * Call a NoOp method on an application using the correct ARC-4 selector.
 * extraFee=true sets fee = 2x the network minimum to cover one inner transaction
 * (1x outer + 1x inner). The minimum is read from suggestedParams so we
 * automatically track any future on-chain fee changes instead of hard-coding 1000.
 */
async function callMethod(
  algodClient: algosdk.Algodv2, sender: string, appId: number,
  selector: Uint8Array, signTransaction: SignFn,
  extraFee = false,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  const minFee = Number(params.minFee ?? params.fee ?? 1000) || 1000
  const txn = algosdk.makeApplicationCallTxnFromObject({
    sender, appIndex: appId,
    onComplete: algosdk.OnApplicationComplete.NoOpOC,
    suggestedParams: extraFee ? { ...params, fee: minFee * 2, flatFee: true } : params,
    appArgs: [selector],
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  await algosdk.waitForConfirmation(algodClient, txnId, 4)
  return txnId
}

export async function releaseEscrowFunds(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  signTransaction: SignFn,
): Promise<string> {
  return callMethod(algodClient, senderAddress, appId, SEL.release, signTransaction, true)
}

/** ARC-4 selector for AgentEscrowVaultV2.release(uint64)uint64. */
const SEL_RELEASE_V2 = new Uint8Array([0x61, 0x17, 0xcc, 0xb8])

/**
 * Release funds from an Agent Escrow Vault v2. v2 takes an explicit `amount`
 * (microAlgos) and writes a BillingRecord into Box Storage. Only the creator
 * or the named agent can call this.
 */
export async function releaseAgentVaultV2(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  amountMicroAlgos: number, signTransaction: SignFn,
  proof?: string,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  const minFee = Number(params.minFee ?? params.fee ?? 1000) || 1000
  const noteBytes = proof ? clampNoteBytes(`ub:proof-of-delivery:${proof}`, 900) : undefined
  const txn = algosdk.makeApplicationCallTxnFromObject({
    sender: senderAddress, appIndex: appId,
    onComplete: algosdk.OnApplicationComplete.NoOpOC,
    suggestedParams: { ...params, fee: minFee * 2, flatFee: true },
    appArgs: [SEL_RELEASE_V2, algosdk.encodeUint64(amountMicroAlgos)],
    boxes: [{ appIndex: appId, name: new Uint8Array(0) }],
    note: noteBytes,
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  await algosdk.waitForConfirmation(algodClient, txnId, 4)
  return txnId
}

/**
 * Release vault funds and attach a free-form proof-of-delivery note to the
 * application call transaction. The note is stored permanently in the
 * transaction record on Algorand and can be retrieved by anyone, making
 * it a tamper-proof receipt that the merchant delivered the service.
 *
 * Used for v1-style vaults (DisputeEscrow, EscrowVault, MultiSigEscrow,
 * TimeLockEscrow, ASAEscrow) whose `release()void` selector takes no args.
 * For Agent Escrow Vault v2, call `releaseAgentVaultV2` instead.
 */
export async function releaseEscrowFundsWithProof(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  proof: string, signTransaction: SignFn,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  const minFee = Number(params.minFee ?? params.fee ?? 1000) || 1000
  const note = clampNoteBytes(`ub:proof-of-delivery:${proof}`, 900)
  const txn = algosdk.makeApplicationCallTxnFromObject({
    sender: senderAddress, appIndex: appId,
    onComplete: algosdk.OnApplicationComplete.NoOpOC,
    suggestedParams: { ...params, fee: minFee * 2, flatFee: true },
    appArgs: [SEL.release],
    note,
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  await algosdk.waitForConfirmation(algodClient, txnId, 4)
  return txnId
}

/**
 * Encode a note string and trim it to fit within `maxBytes` UTF-8 bytes
 * without breaking a multi-byte codepoint. Algorand's per-txn note ceiling
 * is 1024 bytes; we keep a small safety margin.
 */
function clampNoteBytes(s: string, maxBytes: number): Uint8Array {
  const enc = new TextEncoder()
  let bytes = enc.encode(s)
  if (bytes.length <= maxBytes) return bytes
  // Walk back to a safe codepoint boundary.
  let str = s
  while (bytes.length > maxBytes) {
    str = str.slice(0, -1)
    bytes = enc.encode(str)
  }
  return bytes
}

// ── Box Storage: AgentEscrowVaultV2 billing history ────────────────────────

export interface BillingRecord {
  cycle: number
  timestamp: number  // unix seconds
  amount: number     // microAlgos
}

/**
 * Read all on-chain BillingRecords from an AgentEscrowVaultV2 contract.
 * Each release writes a box keyed by "h:<cycle>" (uint64 big-endian) holding
 * a 24-byte struct (timestamp:uint64, amount:uint64, cycle_index:uint64).
 *
 * Returns the records sorted oldest → newest. Falls back to an empty array
 * if the application has no boxes (e.g. legacy v1 vault).
 */
export async function getVaultBillingHistory(
  algodClient: algosdk.Algodv2, appId: number,
): Promise<BillingRecord[]> {
  let resp: any
  try {
    resp = await algodClient.getApplicationBoxes(appId).do()
  } catch {
    return []
  }
  const boxes: Array<{ name: Uint8Array }> = resp?.boxes ?? []
  const out: BillingRecord[] = []
  for (const b of boxes) {
    const name = b.name instanceof Uint8Array ? b.name : new Uint8Array(b.name)
    // We only care about boxes prefixed with "h:" (0x68, 0x3a)
    if (name.length < 3 || name[0] !== 0x68 || name[1] !== 0x3a) continue
    try {
      const value = await algodClient.getApplicationBoxByName(appId, name).do()
      const v: Uint8Array = value?.value instanceof Uint8Array ? value.value : new Uint8Array(value?.value ?? [])
      if (v.length < 24) continue
      const timestamp = Number(algosdk.decodeUint64(v.slice(0, 8), "safe"))
      const amount = Number(algosdk.decodeUint64(v.slice(8, 16), "safe"))
      const cycle = Number(algosdk.decodeUint64(v.slice(16, 24), "safe"))
      out.push({ cycle, timestamp, amount })
    } catch {
      // Skip unreadable box but keep going.
    }
  }
  out.sort((a, b) => a.cycle - b.cycle)
  return out
}

export async function killEscrowContract(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  signTransaction: SignFn,
): Promise<string> {
  return callMethod(algodClient, senderAddress, appId, SEL.kill, signTransaction, true)
}

export async function approveMultiSig(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  signTransaction: SignFn,
): Promise<string> {
  return callMethod(algodClient, senderAddress, appId, SEL.approve, signTransaction, true)
}

export async function deleteEscrowContract(
  algodClient: algosdk.Algodv2, senderAddress: string, appId: number,
  signTransaction: SignFn,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  const minFee = Number(params.minFee ?? params.fee ?? 1000) || 1000
  const txn = algosdk.makeApplicationCallTxnFromObject({
    sender: senderAddress, appIndex: appId,
    onComplete: algosdk.OnApplicationComplete.DeleteApplicationOC,
    suggestedParams: { ...params, fee: minFee * 2, flatFee: true },
    appArgs: [SEL.delete],
  })
  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  await algosdk.waitForConfirmation(algodClient, txnId, 4)
  return txnId
}

// ── NFT receipt minting (ARC-3 compliant + immutable) ──────────────────────
//
// Strict ARC-3 requirements we now satisfy:
//   • assetURL ends with "#arc3" and points to the JSON metadata
//     (we use a `data:` URI so no IPFS pinning is required)
//   • assetMetadataHash = SHA-256 of the metadata JSON bytes
//   • All four roles (manager, reserve, freeze, clawback) are UNSET → asset
//     is permanently immutable. Even the user who minted it cannot tamper
//     with it after the txn confirms.
//
// Spec: https://arc.algorand.foundation/ARCs/arc-0003

async function sha256Bytes(bytes: Uint8Array): Promise<Uint8Array> {
  const hash = await crypto.subtle.digest("SHA-256", bytes as BufferSource)
  // Force a brand-new Uint8Array (not a typed-array view onto an ArrayBuffer)
  // because algosdk v3's strict type guards reject the latter with the
  // confusing "Argument must be byte array" error.
  const out = new Uint8Array(32)
  out.set(new Uint8Array(hash))
  return out
}

export async function mintNFTReceipt(
  algodClient: algosdk.Algodv2, senderAddress: string, vaultAppId: number,
  amount: number, recipientAddress: string,
  signTransaction: SignFn,
): Promise<{ assetId: number; txnId: string }> {
  const params = await algodClient.getTransactionParams().do()

  // ARC-3 metadata. Schema: https://arc.algorand.foundation/ARCs/arc-0003
  const metadata = {
    name: `Unsubscribely Receipt #${vaultAppId}`,
    description: `Verifiable payment receipt: ${amount} ALGO released from escrow vault ${vaultAppId} to ${recipientAddress}.`,
    decimals: 0,
    properties: {
      app_id: vaultAppId,
      amount_algo: amount,
      recipient: recipientAddress,
      payer: senderAddress,
      timestamp: new Date().toISOString(),
      issuer: "Unsubscribely",
    },
  }
  const metadataJson = JSON.stringify(metadata)
  const metadataBytes = new TextEncoder().encode(metadataJson)
  const metadataHash = await sha256Bytes(metadataBytes)

  // ARC-3 marker URL, must be ≤96 bytes (algosdk hard limit). The metadata
  // hash above cryptographically anchors the JSON; the URL just needs the
  // `#arc3` fragment + a stable identifier. Domain is env-driven so we never
  // bake an unowned URL into immutable on-chain receipts.
  const receiptDomain =
    (import.meta.env.VITE_RECEIPT_DOMAIN as string | undefined) || "unsubly2.vercel.app"
  const assetUrl = `https://${receiptDomain}/r/${vaultAppId}#arc3`

  const txn = algosdk.makeAssetCreateTxnWithSuggestedParamsFromObject({
    sender: senderAddress,
    suggestedParams: params,
    total: 1,
    decimals: 0,
    defaultFrozen: false,
    unitName: "RCPT",
    assetName: `Receipt-${vaultAppId}@arc3`,
    assetURL: assetUrl,
    assetMetadataHash: metadataHash,
    // CRITICAL, leave manager/reserve/freeze/clawback UNDEFINED so the
    // asset is permanently immutable.
    note: new TextEncoder().encode(metadataJson.slice(0, 1000)),
  })

  const signedTxns = await signTransaction(txn)
  const sendResponse = await algodClient.sendRawTransaction(signedTxns[0]).do()
  const txnId = extractTxId(sendResponse)
  const result = await algosdk.waitForConfirmation(algodClient, txnId, 4) as any
  // algosdk v3 returns assetIndex as a bigint at multiple possible paths
  const rawId =
    result?.assetIndex ??
    result?.["asset-index"] ??
    result?.applicationIndex ??
    result?.["application-index"] ??
    result?.["created-asset-index"] ??
    0
  const assetId = typeof rawId === "bigint" ? Number(rawId) : Number(rawId)
  if (!assetId) {
    throw new Error(
      `NFT receipt minted but assetId could not be parsed from confirmation. txnId=${txnId}. ` +
      `Inspect the txn on Lora to retrieve the asset id manually.`
    )
  }
  return { assetId, txnId }
}

// ── Service Registry write ─────────────────────────────────────────────────
//
// ARC-4 ABI-method call into the on-chain ServiceRegistry contract. We use
// algosdk's ABIMethod here (instead of a hand-rolled selector + manual encode)
// because the method takes string args of variable length, ABIMethod handles
// the length-prefixing for us, matching exactly what puyapy compiled.
//
// The contract enforces "only original provider can update", no anti-spam
// fee is checked on-chain in the live App ID, so we keep the call minimal.
const REGISTER_METHOD = new algosdk.ABIMethod({
  name: "register",
  args: [
    { type: "string", name: "service_id" },
    { type: "uint64", name: "price_microalgos" },
    { type: "uint64", name: "cycle_days" },
    { type: "string", name: "name" },
  ],
  returns: { type: "void" },
})

// Build the box name the contract uses to store this listing.
// puyapy BoxMap with key_prefix="svc:" stores as `b"svc:" + ABI(arc4.String)(key)`.
// ABI string encoding = uint16 BE length prefix + UTF-8 bytes.
function buildServiceBoxName(serviceId: string): Uint8Array {
  const idBytes = new TextEncoder().encode(serviceId)
  const out = new Uint8Array(4 + 2 + idBytes.length)
  out.set([0x73, 0x76, 0x63, 0x3a], 0) // "svc:"
  out[4] = (idBytes.length >> 8) & 0xff
  out[5] = idBytes.length & 0xff
  out.set(idBytes, 6)
  return out
}

export async function registerService(
  algodClient: algosdk.Algodv2,
  senderAddress: string,
  registryAppId: number,
  service: { service_id: string; price_microalgos: number; cycle_days: number; name: string },
  signTransaction: SignFn,
): Promise<string> {
  const params = await algodClient.getTransactionParams().do()
  // Box-storage requires explicit box references on the app call. Otherwise
  // the AVM rejects the access with "invalid Box reference".
  const boxName = buildServiceBoxName(service.service_id)
  const atc = new algosdk.AtomicTransactionComposer()
  atc.addMethodCall({
    appID: registryAppId,
    method: REGISTER_METHOD,
    methodArgs: [
      service.service_id,
      BigInt(Math.max(0, Math.floor(service.price_microalgos))),
      BigInt(Math.max(1, Math.floor(service.cycle_days))),
      service.name,
    ],
    sender: senderAddress,
    suggestedParams: params,
    boxes: [{ appIndex: registryAppId, name: boxName }],
    signer: async (txnGroup, indexesToSign) => {
      // Bridge our SignFn (single-txn signer) into AtomicTransactionComposer's
      // signer interface, which expects an array of signed bytes.
      const out: Uint8Array[] = []
      for (const i of indexesToSign) {
        const signed = await signTransaction(txnGroup[i])
        out.push(signed[0])
      }
      return out
    },
  })
  const result = await atc.execute(algodClient, 4)
  return result.txIDs[0]
}

